// This script below is auto generated by Auto-Fix Script Generator. Please see links below for reference
// Guide: https://abbott.sharepoint.com/sites/US-BTS-DesignOps/SitePages/Accessibe-setup.aspx
// Script Generator: https://developer.crownpeak.com/autofix/Generatescript.html

let s = document.createElement('script');
let h = document.querySelector('head') || document.body;
s.src = 'https://acsbapp.com/apps/app/dist/js/app.js';
s.async = true;
s.onload = function(){
    acsbJS.init({
    statementLink : '',
    footerHtml : 'Powered By Abbott',
    hideMobile : false,
    hideTrigger : false,
    disableBgProcess: false,
    language : 'en',
    position : 'left',
    leadColor : '#146ff8',
    triggerColor : '#146ff8',
    triggerRadius : '50%',
    triggerPositionX : 'left',
    triggerPositionY : 'bottom',
    triggerIcon : 'default',
    triggerSize : 'medium',
    triggerOffsetX : 20,
    triggerOffsetY : 20,
    mobile : {
    triggerSize: 'small',
    triggerPositionX : 'left',
    triggerPositionY : 'center',
    triggerOffsetX : 0,
    triggerOffsetY : 0,
    triggerRadius : '50%'
    }
    });
};
h.appendChild(s);

$(document).ready(function () {
    if($('#section-sidePanel').length > 0)
        document.getElementById("section-sidePanel").parentNode.classList.add("sticky-sidenav");
});