export const GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST = 'GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST';
export const GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST_SUCCESS = 'GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST_SUCCESS';
export const GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST_FAILURE = 'GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST_FAILURE';

export const getAvailablePaymentMethodsGraphqlRequest = (payload) => ({
	type: GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST, payload
});

export const getAvailablePaymentMethodsGraphqlRequestSuccess = payload => ({
	type: GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST_SUCCESS, payload
});

export const getAvailablePaymentMethodsGraphqlRequestFailure = error => ({
	type: GET_AVAILABLE_PAYMENT_METHODS_GRAPHQL_REQUEST_FAILURE, error
});
