export default {
  mountingPoints: {
    productPrice: '.js-product-price',
    productSubscriptionOptions: '.js-subscription-options',
    productAddToCart: '.js-add-to-cart',
    cartTrigger: '.header__cartTrigger',
    miniCart: '#minicart',
    checkoutFormData: '.checkout-form-data',
    checkoutForm: '.formcontainer #checkout',
    simplifiedCheckoutForm: '.formcontainer #simplified-checkout',
    orderSummary: '#ordersummary',
    orderSummaryPage: '#order-summary-page',
    guestOrderSummaryPage:'#guest-order-summary-page',
    shoppingCart: '#shoppingcart',
    orderDetailsShipmentTracking: '#orderdetailsshipmenttracking',
    orderDetailsItemList: '#orderdetailsitemlist',
    orderDetailsDataDisplay: '#orderdetailsdatadisplay',
    orderDetailsSummary: '#orderdetailssummary',
    orderReturnForm: '#orderreturnform',
    subscriptionDetailsDataDisplay: '#subscriptiondetailsdatadisplay',
    subscriptionDetailsSummary: '#subscriptiondetailssummary',
    shippingMethods: '.js-shipping-methods',
    payOnForm: '.js-payon-checkout',
    paymentTabs: '#checkout-payment-tabs,[data-payment-tabs]',
    producTileInclude: '.js-product-tile-include',
    accountNavigation: '.js-account-navigation',
    myAccountOverview: '#my-account-overview',
    myAccountDetailsForm: '#my-details__form',
    myAccountAddressForm: '#my-account-address-form',
    myAccountCardsForm: '#my-account-cards-form',
    myAccountCardsModal: '#my-card-add-modal',
    myAccountSubscriptions: '.js-subscriptions',
    loadingSpinner: '#loading-indicator',
    orderHistory: '.js-order-history',
    subscriptionHistory: '.js-subscription-history',
    logInLink: '#logInLink',
    autoSubmitForm: '#autosubmit',
    unsubscribeForm: '#unsubscribe-form',
    updateConsents: '#section-update-consents-form',
    placeOrder: '.js-place-order',
    body: 'body',
    columnControlCarousel: '.js-columncontrol-mobile-carousel',
    articleList: '.js-article-list',
    mobileApp: '.ab-mobile-app',
    ReturnLabel: '#returnLabel',
    cancelActiveSubscription: '.cancel-active-subscription',
  },
};
