def agentLabelPrefix = 'AEM65_'
def controlJobBaseName = 'BTS_191_AEM_65/AEM Cloud/aem65-platformcontrol-apps-trigger/'
def controlJobName = controlJobBaseName + java.net.URLEncoder.encode(BRANCH_NAME, "UTF-8")

def environment = getEnvironment(env.BRANCH_NAME)
def controlEnvName =java.net.URLEncoder.encode(BRANCH_NAME.replaceAll('^release/', ''), 'UTF-8').toUpperCase()
def agentLabel = agentLabelPrefix + getAgentSuffix(environment)

pipeline {
  agent { label agentLabel }

  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '30', daysToKeepStr: '60'))
  }

  stages {
    stage('Build') {
      steps {
         withCredentials([usernamePassword(credentialsId: 'ARTIFACTORY7_CRED', passwordVariable: 'PASSWORD_VAR', usernameVariable: 'USERNAME_VAR')])
        {
        withMaven(maven: 'Maven-3-6',
          mavenSettingsConfig: 'aem_local_settings',
          mavenLocalRepo: "${env.WORKSPACE}/.m2") {
          sh 'mvn -B -U clean package -Dserver.username=${USERNAME_VAR} -Dserver.password=${PASSWORD_VAR}'
        }
        }
      }
    }

    stage('Deploy Snapshot') {
      when {
        branch 'release/dev'
      }
      steps {
        rtMavenResolver (
          id: 'mavenResolver',
          serverId: 'Toolchain-Artifactory-7',
          releaseRepo: 'bts-aem-191-maven-virtual',
          snapshotRepo: 'bts-aem-191-maven-virtual'
        )
        rtMavenDeployer (
          id: 'mavenDeployer',
          serverId: 'Toolchain-Artifactory-7',
          releaseRepo: 'bts-aem-191-releases-maven-local',
          snapshotRepo: 'bts-aem-191-maven-snapshots-local',
        )
        rtMavenRun (
          tool: 'Maven-3-8-1',
          pom: 'pom.xml',
          goals: 'clean install  -B -U -PdisableOakIndexesForDeploy',
          resolverId: 'mavenResolver',
          deployerId: 'mavenDeployer'
        )
      }
    }
	
    stage('Sonar Code Analysis') {
      when {
        branch 'release/*'
      }
      steps {
       script {
          if (controlEnvName == 'STABLE'){
            echo "Setting sonarqube controlEnvName: STABLE --> STAGE "
            controlEnvName = "STAGE"
          } else {
            echo "Setting sonarqube controlEnvName: ${controlEnvName} "
          }
          if (controlEnvName in ['STAGE','DEV', 'DEV2', 'QA', 'QA2']){
            echo "Trigarring sonarqube for controlEnvName: ${controlEnvName} "
            scannerHome = tool 'sonarscanner-prod'
            withSonarQubeEnv(credentialsId: 'sonarqube-token', installationName:'SonarQube') {
              sh "${scannerHome}/bin/sonar-scanner \
              -Dsonar.projectKey=191_CLOUD_AEM65-CLOUDPLATFORM-APPS_${controlEnvName} \
              -Dsonar.projectName=191_CLOUD_AEM65-CLOUDPLATFORM-APPS_${controlEnvName} \
              -Dsonar.projectVersion='1.0' \
              -DsonarRunner.aemVersion='6.6' \
              -Dsonar.java.source='11' \
              -Dsonar.java.binaries='./' \
              -Dsonar.sourceEncoding='UTF-8'\
              -Dsonar.java.libraries=\"**/target/classes/*,${env.HOME}/.m2/repository/org/projectlombok/lombok/**/*.jar\"\
              -Dsonar.sources='core/src/main/java, search.core/src/main/java, ui.apps/src/main/content/jcr_root' \
              -Dsonar.coverage.jacoco.xmlReportPaths='core/target/site/jacoco/jacoco.xml, search.core/target/site/jacoco/jacoco.xml'\
              -Dsonar.test.exclusions='ui.apps/src/main/content/jcr_root/apps/**'\
              -Dsonar.coverage.exclusions='ui.apps/src/main/content/jcr_root/apps/**,core/src/main/java/com/abbott/aem/cloud/**/**/model*/*.java,core/src/main/java/com/abbott/aem/cloud/api/configuration/*.java,core/src/main/java/com/abbott/aem/cloud/platform/core/cloudconfig/*.java,core/src/main/java/com/abbott/aem/cloud/platform/core/constants/*.java'\
              -Dsonar.exclusions='ui.apps/src/main/content/jcr_root/apps/abbott-cloudplatform/clientlibs/clientlib-thirdparty/**'"
            }
          }
        }
      }
    }

    stage('Trigger Control Build') {
      when {
        branch 'release/*'
      }
      steps {
        build(job: controlJobName, propagate: false, wait: false)
      }
    }
  }
  
  post {
    cleanup {
      cleanWs() /* clean up our workspace */
    }
  }
}

String getEnvironment(branch) {
  def branchParts = branch.split('/')
  return branchParts[branchParts.length - 1]
}

String getAgentSuffix(environment) {
  if (environment.startsWith('release/stable')) {
    return 'STAGE'
  } else if (environment.startsWith('release/qa')) {
    return 'QA'
  }
  return 'DEV'
}
