const $globals = {
    warningMsgProductSearchResults: `<p class="text-center">
            <strong>Don't drop anything in this container. Dynamic content will override the component.
            Just id allocation is enough.</strong>
                            </p>`,
    warningMsgProductIcons: `<p class="text-center">
            <strong>Icon buttons to be iterated on every product. Use buttons only</strong>
                </p>`,
    countryDefaultText: 'Country',
    languageDefaultText: 'Language',
    categoryDefaultText: 'Category',
    subCategoryDefaultText: 'Sub category',
    productsDefaultText: 'Products',
    fieldErrorBackground: '#ffeaf1',
    countryLanguageQueryParamManuals: "referenceType=language_code",
    contactUsShowFilterWordCount: $('#contactUsShowFilterWordCount').length ? parseInt($('#contactUsShowFilterWordCount').val()) : 2,
    noFavoritesText: $('#noFavoritesText').length ? $('#noFavoritesText').val() : 'You have no favorite documents',
    favoritesPageLimitCount: $('#favoritesPageLimitCount').length ? parseInt($('#favoritesPageLimitCount').val()) : 4,
    favoritesFiltersLimitCount: $('#favoriteFilterCountLimit').length ? parseInt($('#favoriteFilterCountLimit').val()) : 3,
    productCategoryDefaultLimitCount: 3,
    subCategoryDefaultLimitCount: 6,
    recentlyViewedDefaultLimitCount: $('#recentlyViewedCountLimit').length ? parseInt($('#recentlyViewedCountLimit').val()) : 6,
    categoriesFilterLimitCount: $('#categoriesFilterLimitCount').length ? parseInt($('#categoriesFilterLimitCount').val()) : 3,
    noSearchResultText: $('#noSearchResultText').length ? $('#noSearchResultText').val() : 'No results found',
    searchResultsLimitCount: $('#searchCountLimit').length ? parseInt($('#searchCountLimit').val()) : 10,
    searchResultsIncludeText: $('#searchResultsIncludeText').length ? $('#searchResultsIncludeText').val() : 'Includes',
    searchResultsProductsText: $('#searchResultsProductsText').length ? $('#searchResultsProductsText').val() : 'Products',
    searchKeywordsText: $('#searchKeywordsText').length ? $('#searchKeywordsText').val() : 'Keyword : ',
    filterHeadingTextMobile : $('#filterHeadingTextMobile').length ? $('#filterHeadingTextMobile').val() : 'Filters',
    defaultPaginationLimitCount: 4,
    countryLanguageBaseURL: $('#countryLanguageReferenceURL').length && $('#countryLanguageReferenceURL').find('form').length && $('#countryLanguageReferenceURL').find('form').attr('action') ? $('#countryLanguageReferenceURL').find('form').attr('action') : '',
    countryLanguageQueryParam: $('#countryLanguageReferenceURL').length && $('#countryLanguageReferenceURL').find('[name="requestType"]').length && $('#countryLanguageReferenceURL').find('[name="requestType"]').attr('value') ? $('#countryLanguageReferenceURL').find('[name="requestType"]').attr('value') : '',
    countryLanguageDefaultURL: '',
    productSearchURL: $('#eslEndPoint').length && $('#eslEndPoint').text() ? $('#eslEndPoint').text() : 'https://dev2.services.abbott/api/public/search/sitesearch',
    eslCountryLangHeaderTemplate:  {
        'Content-Type': 'application/x-www-form-urlencoded',
        'x-application-id': 'aveifu',
        'x-country-code': 'US',
        'x-preferred-language': 'en',
    },
    eslHeaderTemplate: {
                'x-application-id': 'aveifu',
                'x-country-code': 'US',
                'x-preferred-language': 'en',
            },
    languagesList: $('#languagesList').val() ? JSON.parse($('#languagesList').val()) : {
        "English":"en",
        "French":"fr",
        "German":"de",
        "Spanish":"es",
        "Italian":"it",
        "Portuguese":"pt",
        "Swedish":"sv",
        "Dutch":"nl",
        "Danish":"da",
        "Greek":"el",
        "Polish":"pl",
        "Hungarian":"hu",
        "Czech":"cs",
        "Turkish":"tr",
        "Slovak":"sk",
        "Bulgarian":"bg",
        "Romanian":"ro",
        "Russian":"ru",
        "Finnish":"fi",
        "Norwegian":"no",
        "Estonian":"et",
        "Latvian":"lv",
        "Lithuanian":"lt",
        "Slovenian":"sl",
        "Serbian":"sr",
        "Macedonian":"mk",
        "Ukrainian":"uk",
        "Croatian":"hr",
        "Francais":"fr",
        "Deutsch":"de",
        "Espanol":"es",
        "Italiano":"it",
        "Portugues":"pt",
        "Svenska":"sv",
        "Nederlands":"nl",
        "Dansk":"da",
        "Ελληνικά":"el",
        "Polski":"pl",
        "Magyar":"hu",
        "Česky":"cs",
        "Türkce":"tr",
        "Slovensky":"sk",
        "Български":"bg",
        "Română":"ro",
        "Русский":"ru",
        "Suomi":"fi",
        "Norsk":"no",
        "Eesti keel":"et",
        "Latviešu":"lv",
        "Lietuvių":"lt",
        "Hrvatski":"hr",
        "Srpski":"sr",
        "Македонски":"mk",
        "Українська":"uk",
        "Czeh":"cz",
        "Arabic":"ar",
        "Maltese":"mt",
        "Mongolian":"mn",
        "Albanian":"sq",
        "Armenian":"hy",
        "Kazakh":"kk",
        "Chinese":"zh",
        "Icelandic":"is",
        "Indonesian":"in",
        "Hebrew":"iw",
        "Belarusian":"be",
        "Portuguese(brazil)":"pt_br",
        "Luxembourgish":"lb",
        "Kiswahili":"sw",
        "Irish":"ga",
        "Japanese":"ja",
        "Korean":"ko",
        "Somali":"so",
        "Thai":"th",
        "Turkmen":"tk",
        "Uzbek":"uz",
        "Vietnamese":"en",
        "Malay":"ms",
    },
    defaultCountryCode: 'US',
    defaultCountry: 'United States',
    defaultLanguage: 'en',
    detailsPageDefault: $('#detailsPageUrl').length ? $('#detailsPageUrl').val() : '',
    detailsPagePreviousVersionText: 'Previous Versions',
    contactExperienceFragmentUrl: '/content/experience-fragments/av/eifu/contactus-experiencefragments/',
    hcpAndNhcpUrlPages: ['home.html'],
    indexPageRedirectionPage: $('#indexPageRedirectionPage').length ? $('#indexPageRedirectionPage').val() : 'index.html', 
    nhcpBaseUrl: $('#nhcpBaseUrl').length ? $('#nhcpBaseUrl').val() : '',
}